export interface IWeatherListItem {
  
    "lat":34,
    "lon":34,
    "date":"2023-03-28",
    "tz":"+02:00",
    "sunrise":"2023-03-28T05:37:14",
    "sunset":"2023-03-28T18:01:37",
    "irradiance":{
       "daily":[
          {
             "clear_sky":{
                "ghi":6694.67,
                "dni":9166.93,
                "dhi":1140.04
             },
             "cloudy_sky":{
                "ghi":6694.67,
                "dni":8962.1,
                "dhi":1120.64
             }
          }
       ],
       "hourly":[
          {
             "hour":0,
             "clear_sky":{
                "ghi":0,
                "dni":0,
                "dhi":0
             },
             "cloudy_sky":{
                "ghi":0,
                "dni":0,
                "dhi":0
             }
          },
          {
             "hour":1,
             "clear_sky":{
                "ghi":0,
                "dni":0,
                "dhi":0
             },
             "cloudy_sky":{
                "ghi":0,
                "dni":0,
                "dhi":0
             }
          },
          {
             "hour":2,
             "clear_sky":{
                "ghi":0,
                "dni":0,
                "dhi":0
             },
             "cloudy_sky":{
                "ghi":0,
                "dni":0,
                "dhi":0
             }
          },
          {
             "hour":3,
             "clear_sky":{
                "ghi":128.2,
                "dni":477.91,
                "dhi":53.3
             },
             "cloudy_sky":{
                "ghi":128.2,
                "dni":460.36,
                "dhi":47.17
             }
          },
          {
             "hour":4,
             "clear_sky":{
                "ghi":344.02,
                "dni":705.53,
                "dhi":82.21
             },
             "cloudy_sky":{
                "ghi":344.02,
                "dni":709.46,
                "dhi":73.51
             }
          },
          {
             "hour":5,
             "clear_sky":{
                "ghi":553.18,
                "dni":816.73,
                "dhi":100.14
             },
             "cloudy_sky":{
                "ghi":553.18,
                "dni":801.59,
                "dhi":101.82
             }
          },
          {
             "hour":6,
             "clear_sky":{
                "ghi":727.62,
                "dni":879.35,
                "dhi":111.8
             },
             "cloudy_sky":{
                "ghi":727.62,
                "dni":864.5,
                "dhi":115.05
             }
          },
          {
             "hour":7,
             "clear_sky":{
                "ghi":849.19,
                "dni":913.88,
                "dhi":118.8
             },
             "cloudy_sky":{
                "ghi":849.19,
                "dni":906.71,
                "dhi":116.74
             }
          },
          {
             "hour":8,
             "clear_sky":{
                "ghi":906.35,
                "dni":928.27,
                "dhi":121.84
             },
             "cloudy_sky":{
                "ghi":906.35,
                "dni":909.35,
                "dhi":129.82
             }
          },
          {
             "hour":9,
             "clear_sky":{
                "ghi":893.86,
                "dni":925.25,
                "dhi":121.17
             },
             "cloudy_sky":{
                "ghi":893.86,
                "dni":908.83,
                "dhi":126.93
             }
          },
          {
             "hour":10,
             "clear_sky":{
                "ghi":812.89,
                "dni":904.28,
                "dhi":116.75
             },
             "cloudy_sky":{
                "ghi":812.89,
                "dni":903.82,
                "dhi":109.46
             }
          },
          {
             "hour":11,
             "clear_sky":{
                "ghi":670.94,
                "dni":861.15,
                "dhi":108.19
             },
             "cloudy_sky":{
                "ghi":670.94,
                "dni":855.43,
                "dhi":104.91
             }
          },
          {
             "hour":12,
             "clear_sky":{
                "ghi":481.8,
                "dni":784.81,
                "dhi":94.59
             },
             "cloudy_sky":{
                "ghi":481.8,
                "dni":778.52,
                "dhi":90.92
             }
          },
          {
             "hour":13,
             "clear_sky":{
                "ghi":266.39,
                "dni":645.45,
                "dhi":73.66
             },
             "cloudy_sky":{
                "ghi":266.39,
                "dni":644.9,
                "dhi":66.16
             }
          },
          {
             "hour":14,
             "clear_sky":{
                "ghi":60.24,
                "dni":324.33,
                "dhi":37.59
             },
             "cloudy_sky":{
                "ghi":60.24,
                "dni":218.62,
                "dhi":38.14
             }
          },
          {
             "hour":15,
             "clear_sky":{
                "ghi":0,
                "dni":0,
                "dhi":0
             },
             "cloudy_sky":{
                "ghi":0,
                "dni":0,
                "dhi":0
             }
          },
          {
             "hour":16,
             "clear_sky":{
                "ghi":0,
                "dni":0,
                "dhi":0
             },
             "cloudy_sky":{
                "ghi":0,
                "dni":0,
                "dhi":0
             }
          },
          {
             "hour":17,
             "clear_sky":{
                "ghi":0,
                "dni":0,
                "dhi":0
             },
             "cloudy_sky":{
                "ghi":0,
                "dni":0,
                "dhi":0
             }
          },
          {
             "hour":18,
             "clear_sky":{
                "ghi":0,
                "dni":0,
                "dhi":0
             },
             "cloudy_sky":{
                "ghi":0,
                "dni":0,
                "dhi":0
             }
          },
          {
             "hour":19,
             "clear_sky":{
                "ghi":0,
                "dni":0,
                "dhi":0
             },
             "cloudy_sky":{
                "ghi":0,
                "dni":0,
                "dhi":0
             }
          },
          {
             "hour":20,
             "clear_sky":{
                "ghi":0,
                "dni":0,
                "dhi":0
             },
             "cloudy_sky":{
                "ghi":0,
                "dni":0,
                "dhi":0
             }
          },
          {
             "hour":21,
             "clear_sky":{
                "ghi":0,
                "dni":0,
                "dhi":0
             },
             "cloudy_sky":{
                "ghi":0,
                "dni":0,
                "dhi":0
             }
          },
          {
             "hour":22,
             "clear_sky":{
                "ghi":0,
                "dni":0,
                "dhi":0
             },
             "cloudy_sky":{
                "ghi":0,
                "dni":0,
                "dhi":0
             }
          },
          {
             "hour":23,
             "clear_sky":{
                "ghi":0,
                "dni":0,
                "dhi":0
             },
             "cloudy_sky":{
                "ghi":0,
                "dni":0,
                "dhi":0
             }
          }
       ]
    }
 
}

export interface IWeatherData {
//   apiKey: "e22480dc6d550a7618459593bdbe5594";
  apiKey: string | null;
  lat: string | null;
  lon: string | null;
  date: string | null;
}

export interface ICitiesPayloadData {
  weatherApiKey: "c3dbf9ec078345588f091658231504"; // WEATHeR API KEY
//  apiUserName: string; // Ваш логин на GeoNames
//  countryCode: string; // Код страны (для Кыргызстана - 'KG')
//  maxRows: number; // Максимальное количество результатов (от 1 до 1000)
}